In [2]:
#建立list
a = [1, 3, 5, 7, 9]
a * 2

b = [2, 4, 6, 8, 10]
a + b

resulf = []
for i in range(5):
    resulf.append(a[i] + b[i])

resulf

[3, 7, 11, 15, 19]

In [4]:
import numpy as np

#透過list建立ndArray

a_array = numpy.array([1, 3, 5, 7, 9])
a_array * 2

b_array = numpy.array([2, 4, 6, 8, 10])

a_array + b_array

array([ 3,  7, 11, 15, 19])

In [24]:
#使用python建立5個亂數元素的list
import random

#list comprehension
[random.randint(50,100) for _ in range(5)]

[76, 66, 98, 64, 68]

In [31]:
#使用numpy random 建立亂數
import numpy as np
np.random.randint(50,high=100,size=5)

array([71, 63, 66, 89, 73])

In [47]:
np.random.randint(50,high=100,size=(50, 5))

array([[79, 52, 83, 76, 84],
       [86, 57, 97, 63, 61],
       [96, 82, 53, 62, 62],
       [77, 61, 78, 75, 67],
       [88, 91, 82, 93, 93],
       [69, 58, 98, 91, 53],
       [79, 55, 89, 69, 76],
       [95, 99, 77, 75, 53],
       [72, 92, 56, 82, 53],
       [77, 92, 76, 78, 64],
       [66, 52, 74, 83, 58],
       [92, 91, 96, 69, 57],
       [74, 74, 76, 51, 65],
       [73, 54, 81, 66, 71],
       [97, 96, 63, 76, 50],
       [86, 89, 66, 64, 72],
       [68, 70, 63, 91, 61],
       [73, 85, 94, 79, 96],
       [57, 82, 83, 73, 65],
       [66, 84, 68, 67, 57],
       [78, 89, 75, 98, 54],
       [75, 66, 93, 79, 96],
       [82, 57, 97, 85, 54],
       [82, 84, 93, 93, 52],
       [78, 67, 56, 85, 56],
       [88, 55, 97, 63, 57],
       [90, 69, 69, 93, 86],
       [90, 61, 87, 52, 74],
       [97, 66, 80, 71, 64],
       [78, 98, 53, 76, 63],
       [72, 80, 57, 63, 83],
       [85, 68, 50, 62, 94],
       [62, 80, 68, 60, 90],
       [74, 74, 93, 90, 97],
       [70, 66